### PR TITLE
Explicitly list packages in setup.py instead of using find_packages

### PR DESCRIPTION
**Pull request by barakalon**
The package isn't getting built properly. This seems to fix the problem, although I haven't had time to dig into why yet.

### CODE REVIEW

**Comment by barakalon** [comment]
I'm pretty sure this will fix https://github.com/plangrid/soql/issues/4

@Ben-G , sorry to bug you with this one... I've just semi-arbitrarily chosen you as PlanGrid's open-source tsar 😁

Looks like I'll need a review here. 
I'll also need someone to release to PyPI - these directions should work: https://github.com/plangrid/soql/blob/master/CONTRIBUTING.rst#releasing-to-pypi, but if something goes wrong I'm happy to help debug.

If there's someone else at PlanGrid that's happy to be the point person for this repo (and maybe also https://github.com/plangrid/flask-rebar), let me know! (maybe @juliusiv ?)

**Review by Ben-G — APPROVED** [review]
🚢

**Comment by Ben-G** [comment]
@barakalon I will follow-up on the release / ownership question. But I'm a good point person for now.

**Comment by barakalon** [comment]
Cool. 
I'd like to get this released ASAP, since, as @mpktarvin points out in https://github.com/plangrid/soql/issues/4, this package currently isn't even installable. Let me know if there's anything I can do.

**Comment by juliusiv** [comment]
do i need write access or something to push the new version?

**Pull request merged**
