### PR TITLE
Bump version: 1.0.1 → 1.0.2

### PR DESCRIPTION
**Pull request by juliusiv**
@Ben-G can you review this release?

### CODE REVIEW

**Comment by barakalon** [comment]
The way tagging works with travis-ci is a bit tricky - let me know if this doesn't work

**Review by Ben-G — APPROVED** [review]
🚀

**Comment by juliusiv** [comment]
@barakalon not sure this worked because when i tried installing `soql` i got v1.0.1. also pypi still says that's the version https://pypi.org/project/soql/

**Comment by juliusiv** [comment]
fwiw i could have done something wrong. i manually bumped the version because `bumpversion` was complaining about things

**Comment by barakalon** [comment]
Ah, what was `bumpversion` complaining about?

I think you missed the "v" for the version tag. https://github.com/plangrid/soql/blob/master/.travis.yml#L17

travis-ci is also a good place to poke around for debugging: https://travis-ci.org/plangrid/soql

**Comment by barakalon** [comment]
_Might_ be able to just create the proper tag on the master branch and then push that

**Comment by juliusiv** [comment]
ah shite. it was spewing this:
```
Traceback (most recent call last):
  File "/Users/jalexander/.virtualenvs/soql/bin/bumpversion", line 11, in <module>
    sys.exit(main())
  File "/Users/jalexander/.virtualenvs/soql/lib/python3.6/site-packages/bumpversion/__init__.py", line 994, in main
    vcs.commit(message=commit_message)
  File "/Users/jalexander/.virtualenvs/soql/lib/python3.6/site-packages/bumpversion/__init__.py", line 73, in commit
    list(os.environ.items()) + [(b'HGENCODING', b'utf-8')]
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'commit', '-F', '/var/folders/8m/zmzdhqtd139g5k2_nxf6hmh92lylxp/T/tmpinl8mfij']' returned non-zero exit status 1.
```
i'll fixup the tag and rerun the CI

**Comment by juliusiv** [comment]
cool looks like it worked. 1.0.2 is out

**Comment by barakalon** [comment]
Thanks @juliusiv !

**Pull request merged**
